#!/usr/bin/env Rscript

#   Three-group multinomial logistic regression for PhIP-seq viral seropositivity
#   using the viral hit-fraction calling method.
#
#   Extends Multi_Plate_Case_Control_VirHitFrac_Seropositivity_Regression.R from
#   two groups to three by replacing binary logistic regression (glm / binomial)
#   with multinomial logistic regression (nnet::multinom).  The original two-group
#   scripts are unchanged; this script lives alongside them.
#
#   Model
#   -----
#   For every virus, fit:
#       group ~ virus [+ age] [+ sex] [+ plate] [+ lane]
#   where group is a three-level factor with group1 as the reference.
#   This yields two sets of coefficients per virus:
#       group2 vs. group1
#       group3 vs. group1
#
#   Output columns (per virus, sorted by ascending min p-value):
#       species,
#       freq_<group1>, freq_<group2>, freq_<group3>,
#       beta_<group2>_vs_<group1>, se_<group2>_vs_<group1>, pval_<group2>_vs_<group1>,
#       beta_<group3>_vs_<group1>, se_<group3>_vs_<group1>, pval_<group3>_vs_<group1>
#
#   Usage example:
#       module load r
#       Multi_Plate_Three_Group_VirHitFrac_Seropositivity_Regression.R \
#           -z 5 --type "pemphigus serum" \
#           -a "PF Patient" -b "Non Endemic Control" -c "Healthy Control" \
#           --zfile_basename Zscores.csv \
#           -o /path/to/output \
#           -p /path/to/out.plate13 -p /path/to/out.plate14 \
#           -p /path/to/out.plate21
#
#   Prerequisites: the per-plate Viral_Frac_Hits_*.csv files must already exist
#   (generated by the same upstream step used for the two-group version).
#
#   Dependencies: argparse, data.table, nnet, fs
#   Sourced libs:  GenoLib.R       (read_multiple_manifests)
#                  ThreeGroupLib.R (build_datfile_three_group, select_subjects_three_group,
#                                   multinom_reg, build_formula_three_group,
#                                   init_log_three_group, write_results_three_group)

options(warn = 1)

library("argparse")
args       <- commandArgs()
scriptname <- sub("--file=", "", args[grepl("--file=", args)])
scriptdir  <- dirname(sub("--file=", "", args[grepl("--file=", args)]))
source(paste(scriptdir, "GenoLib.R",       sep = "/"))
source(paste(scriptdir, "ThreeGroupLib.R", sep = "/"))

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

parser <- ArgumentParser(description = scriptname)
parser$add_argument("-s", "--sex", type = "character", default = "",
    help = "limit sex", metavar = "sex")
parser$add_argument("--study", type = "character", action = "append",
    help = "limit study", metavar = "study")
parser$add_argument("-t", "--type", type = "character", default = "",
    help = "limit type", metavar = "type")
parser$add_argument("-a", "--group1", type = "character", required = TRUE,
    help = "first group (reference level)", metavar = "group")
parser$add_argument("-b", "--group2", type = "character", required = TRUE,
    help = "second group (contrasted against group1)", metavar = "group")
parser$add_argument("-c", "--group3", type = "character", required = TRUE,
    help = "third group (contrasted against group1)", metavar = "group")
parser$add_argument("-v", "--virfrac", type = "double", default = 0.05,
    help = "viral hit-fraction threshold [default %(default)s]",
    metavar = "double")
parser$add_argument("-z", "--zscore", type = "double", default = 3.5,
    help = "Z-score threshold used when generating Viral_Frac_Hits files [default %(default)s]",
    metavar = "double")
parser$add_argument("-p", "--plate", type = "character", required = TRUE,
    action = "append",
    help = "plate directory (repeat for each plate)", metavar = "directory")
parser$add_argument("-o", "--output_dir", type = "character", default = "./",
    help = "output directory [default %(default)s]", metavar = "directory")
parser$add_argument("--zfile_basename", type = "character",
    default = "Zscores.csv",
    help = "Z-score file basename used when naming Viral_Frac_Hits files [default %(default)s]",
    metavar = "Zscores file basename")
parser$add_argument("--ignore_plate", action = "store_true",
    help = "exclude plate from the regression formula")
opt <- parser$parse_args()

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

groups_to_compare <- c(opt$group1, opt$group2, opt$group3)
print("Comparing these groups"); print(groups_to_compare)

plates <- opt$plate
print("Comparing these plates"); print(plates)

owd <- opt$output_dir
print("Output dir"); print(owd)
dir.create(owd, showWarnings = FALSE, recursive = TRUE)

library(data.table)

Z_thresh <- opt$zscore
Vir_frac <- opt$virfrac

# Reconstruct the per-plate Viral_Frac_Hits filename exactly as
# Count_Viral_Tile_Hit_Fraction_Three_Group.R names it — all three groups
# are included in the stem so the filename is unambiguous.
virfracfilename <- paste0(
    gsub(" ", "_",
         paste("Viral_Frac_Hits",
               fs::path_ext_remove(basename(opt$zfile_basename)),
               paste(opt$study, collapse = "-"), opt$type,
               paste(groups_to_compare, collapse = "-"),
               "Z", Z_thresh,
               "sex", opt$sex,
               sep = "-")),
    ".csv")

output_base <- paste0(owd, "/", gsub(" ", "_",
    paste("Multiplate_Three_Group_VirFrac_Seropositivity_Comparison",
          fs::path_ext_remove(basename(opt$zfile_basename)),
          paste(opt$study, collapse = "-"), opt$type,
          paste(groups_to_compare, collapse = "-"),
          "Z", Z_thresh,
          "sex", opt$sex,
          "VirFrac", Vir_frac, sep = "-")))

logname <- paste0(output_base, ".log")

init_log_three_group(
    logname  = logname,
    analysis = paste0(
        "Multi-plate three-group multinomial logistic regression for viral ",
        "seropositivity (hit-fraction method), adjusting for age, sex, and plate.\n",
        "Reference group (group1): ", opt$group1, "\n",
        "Z-score threshold = ", Z_thresh, "\n",
        "Viral hit-fraction threshold = ", Vir_frac),
    plates   = plates,
    groups   = groups_to_compare
)

# ---------------------------------------------------------------------------
# Read per-plate viral hit-fraction files
# ---------------------------------------------------------------------------

virfiles <- list()

for (i in seq_along(plates)) {
    virfile <- data.frame(
        data.table::fread(paste0(plates[i], "/", virfracfilename),
                          sep = ",", header = TRUE),
        check.names = FALSE)
    virfiles[[i]] <- virfile
}

manifest <- read_multiple_manifests(plates)
uniq_sub <- select_subjects_three_group(manifest, opt)

cat(paste0("\nTotal included subjects: ", length(uniq_sub)),
    file = logname, append = TRUE, sep = "\n")

# Intersect virus columns across all plates
common_virs <- Reduce(intersect, lapply(virfiles, colnames))
for (i in seq_along(plates))
    virfiles[[i]] <- virfiles[[i]][, common_virs]
common_virs <- common_virs[-1]   # drop the subject-ID column

cat(paste0("\nTotal included viruses: ", length(common_virs)),
    file = logname, append = TRUE, sep = "\n")

# ---------------------------------------------------------------------------
# Convert hit-fraction values to binary viral calls
# ---------------------------------------------------------------------------

cat("\nStart converting viral hit-fraction calls to binary calls",
    file = logname, append = TRUE, sep = "\n")

viral_calls           <- data.frame(matrix(0L, nrow = length(uniq_sub),
                                            ncol = length(common_virs) + 1))
colnames(viral_calls) <- c("ID", common_virs)
viral_calls$ID        <- uniq_sub

for (i in seq_len(nrow(viral_calls))) {
    print(paste("Looping:", i, ":", nrow(viral_calls)))

    id    <- viral_calls$ID[i]
    mp    <- manifest$plate[which(manifest$subject == id)][[1]]
    rloc  <- which(virfiles[[mp]][, 1] == id)[1]

    myCounts     <- data.frame(t(virfiles[[mp]][rloc,
                         which(colnames(virfiles[[mp]]) %in% common_virs)]))
    myCounts[, 1] <- as.numeric(myCounts[, 1])

    if (length(which((common_virs == row.names(myCounts)) == FALSE)) > 0) {
        cat(paste("\nError:", id, ": plate", mp,
                  ": Viruses out of order. This should never appear."),
            file = logname, append = TRUE, sep = "\n")
    }

    viral_calls[i, -1] <- ifelse(myCounts > Vir_frac, 1L, 0L)
}
cat("...Complete.", file = logname, append = TRUE, sep = "\n")

rm(virfiles)

# ---------------------------------------------------------------------------
# Build covariate data frame and model formula
# ---------------------------------------------------------------------------

datfile       <- build_datfile_three_group(uniq_sub, manifest, opt)
datfile$virus <- NA

cat(capture.output(print(head(datfile))), file = logname, append = TRUE, sep = "\n")

formula <- build_formula_three_group(datfile,
                                     predictor    = "virus",
                                     ignore_plate = opt$ignore_plate)
cat(paste("formula", formula), file = logname, append = TRUE, sep = "\n")

# ---------------------------------------------------------------------------
# Per-group counts for frequency calculations
# ---------------------------------------------------------------------------

n_g1 <- sum(datfile$group == opt$group1)
n_g2 <- sum(datfile$group == opt$group2)
n_g3 <- sum(datfile$group == opt$group3)

cat(paste0("\nTotal ", opt$group1, ": ", n_g1), file = logname, append = TRUE, sep = "\n")
cat(paste0("\nTotal ", opt$group2, ": ", n_g2), file = logname, append = TRUE, sep = "\n")
cat(paste0("\nTotal ", opt$group3, ": ", n_g3), file = logname, append = TRUE, sep = "\n")

# ---------------------------------------------------------------------------
# Initialise results table
# ---------------------------------------------------------------------------

g2_vs_g1 <- paste0(opt$group2, "_vs_", opt$group1)
g3_vs_g1 <- paste0(opt$group3, "_vs_", opt$group1)

result_cols <- c(
    "species",
    paste0("freq_", opt$group1),
    paste0("freq_", opt$group2),
    paste0("freq_", opt$group3),
    paste0("beta_", g2_vs_g1), paste0("se_", g2_vs_g1), paste0("pval_", g2_vs_g1),
    paste0("beta_", g3_vs_g1), paste0("se_", g3_vs_g1), paste0("pval_", g3_vs_g1)
)

pvalues           <- data.frame(matrix(NA, nrow = length(common_virs),
                                        ncol = length(result_cols)))
colnames(pvalues) <- result_cols
pvalues$species   <- common_virs

# ---------------------------------------------------------------------------
# Main loop: fit multinomial model per virus
# ---------------------------------------------------------------------------

cat("\nStart loop over virus multinomial regression analysis:",
    file = logname, append = TRUE, sep = "\n")

for (i in seq_along(common_virs)) {
    print(paste("Looping:", i, ":", length(common_virs)))

    datfile$virus <- viral_calls[, which(colnames(viral_calls) == common_virs[i])]

    n_g1_pos <- sum(datfile$virus == 1 & datfile$group == opt$group1)
    n_g2_pos <- sum(datfile$virus == 1 & datfile$group == opt$group2)
    n_g3_pos <- sum(datfile$virus == 1 & datfile$group == opt$group3)

    pvalues[i, paste0("freq_", opt$group1)] <- n_g1_pos / n_g1
    pvalues[i, paste0("freq_", opt$group2)] <- n_g2_pos / n_g2
    pvalues[i, paste0("freq_", opt$group3)] <- n_g3_pos / n_g3

    total_pos <- n_g1_pos + n_g2_pos + n_g3_pos
    total_n   <- n_g1 + n_g2 + n_g3

    if (total_pos %in% c(0, total_n)) {
        next
    }

    results <- multinom_reg(datfile, formula, "virus", logname, opt)

    pvalues[i, paste0("beta_", g2_vs_g1)] <- results$g2[1]
    pvalues[i, paste0("se_",   g2_vs_g1)] <- results$g2[2]
    pvalues[i, paste0("pval_", g2_vs_g1)] <- results$g2[3]

    pvalues[i, paste0("beta_", g3_vs_g1)] <- results$g3[1]
    pvalues[i, paste0("se_",   g3_vs_g1)] <- results$g3[2]
    pvalues[i, paste0("pval_", g3_vs_g1)] <- results$g3[3]
}
cat("...Complete.", file = logname, append = TRUE, sep = "\n")

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------

write_results_three_group(pvalues, output_base)

cat("\nAnalysis complete.", file = logname, append = TRUE, sep = "\n")
